### ISSUE TITLE
Handling model state bindings

### ISSUE THREAD

**Issue by OskarGroth** [davidgarywood/swiftui-router#12]
The demo showcases ViewModels that keep a separate, local state (`isLoggingIn`) or passing on methods to services:

```swift
class AccountScreenViewModel: BaseViewModel<Services>, ObservableObject {
  func logout() {
      self.services.loginManager.logOut()
  }
}
```

But what about when we have UI that requires a binding directly to the state? A TextField, List selection or Toggle for example.
If we imagine that we have a UserManager that has a state for user status:

```swift
public protocol UserManager {
    var userStatus: UserStatus { get }
}

public class UserStatus: ObservableObject {
    @Published var isAway: Bool = false
}
```

And a view for the User with a toggle for their status:

```swift
struct UserScreen: View {
    @State var router: UserScreenRouter    
    @StateObject var viewModel: UserScreenViewModel
    
    var body: some View {
        Toggle("Away", isOn: <Binding<Bool>>)
    }
}
```

And a view model:

```swift
class UserScreenViewModel: BaseViewModel<Services>, ObservableObject {
    
}
```

What should we put in the ViewModel here? Where does the binding go?
We can't bind it directly to viewModel.services.userManager.userStatus.isAway, and even if we could it would not guarantee that the view will refresh properly.
Do we create an intermediary state in the ViewModel that we bind to the original state? I can see it being done like this:

```swift
class UserScreenViewModel: BaseViewModel<Services>, ObservableObject {
    
    @Published var isAway: Bool = false {
        didSet {
            guard oldValue != isAway else { return }
            services.loginManager.state.isAway = isAway
        }
    }
        
    override init(services: Services) {
        super.init(services: services)
        services.loginManager.state.$isAway.removeDuplicates().assign(to: &$isAway)
    }
    
}
```

But it is an annoying bit of setup for what is a very common use case. Have you figured out a better solution?

**Comment by roboheadz** [comment]
This is both a limitation, and one of the principles of the pattern itself. The view models create a local state for the view, and therefore create a bridge between view <-> global state in this way. This does mean an element of duplication / "pass the parcel" goes on.

The upside of this is that the view model itself can perform its own modifications on global state where necessary, our view layer remains decoupled from global state, and this gives us a level of flexibility for refactoring.

I tend to create bindings in my view models, rather than use didSet in this way. This can come in handy for throttling calls to services so they don't get called too often when a user's typing, for example:

```
class LoginViewModel: BaseViewModel<Services>, ObservableObject {
    @Published var searchString: String = ""

    private var cancellables = Set<AnyCancellable>()
  
    override init(services: Services) {
        super.init(services: services)
        self.setBindings()
    }

   private func setBindings() {
        self.$searchString
            .throttle(for: .milliseconds(500), latest: true)
            .sink { [weak self] searchString in
                self?.services.dataManager.search(searchString)
            }
            .store(in: &self.cancellables)           
   }
}
```

**Comment by OskarGroth** [comment]
Thanks for the explanation, it makes sense and I like the separation from global state that this method brings.
The observation with throttling is a nice touch and does solve a lot of performance issues that developers tend to run into while working with SwiftUI 😄 

In my case I wanted two-way observation which is a bit more annoying. There is also a problem in both of our examples that the global state will be assigned upon view model creation, because the initial value given from the observer creation will trigger it to assign it to the global state. So just visiting this view will trigger a global state to update (even if it's to the same value it already was).

I tried cleaning this up a bit and came up with the following:

```
class AccountScreenViewModel: BaseViewModel<Services>, ObservableObject {
    
    @Published var isAway: Bool = false
    
    private var cancellables = Set<AnyCancellable>()
        
    override init(services: Services) {
        super.init(services: services)
        setupBindings()
    }
    
    private func setupBindings() {
        services.loginManager.state.$isAway.assign(to: &$isAway)
        $isAway
            .assignViewModelState(to: \.isAway, on: services.loginManager.state)
            .store(in: &cancellables)
    }
    
}


extension Publisher where Output: Equatable, Failure == Never {
    
    func assignViewModelState<Root>(to keyPath: ReferenceWritableKeyPath<Root, Self.Output>, on object: Root, throttle: Bool = false) -> AnyCancellable {
        self
            .dropFirst()
            .throttle(for: throttle ? .milliseconds(200) : 0, scheduler: RunLoop.main, latest: true)
            .removeDuplicates()
            .assign(to: keyPath, on: object)
    }
    
}
```

Which seems to work pretty well so far.
You should add a section on this to the blog post when you update it next time 👍
