### ISSUE TITLE
Question about new Dependency Injection mechanism

### ISSUE THREAD

**Issue by OskarGroth** [davidgarywood/swiftui-router#16]
I went through the update to the blog post and project, but I'm confused about the new "dependency injection" mechanism via property wrappers.

The new solution to injecting dependencies is to use a new key wrapper that defines access to dependencies:

> Dependencies are brought into ViewModels or Routers by using the @Injected property wrapper along with the keypath for the dependency. e.g: @Injected(\.loginManager) var loginManager will bring the loginManager loaded in DependencyInjection.assembly into a view model.

But isn't this literally just making the previous `AppServices` a singleton? It doesn't look like dependency injection at all to me. You have to hardcode all the available dependencies in advance into `DependencyInjection`, which then just provides global access to them via a keyPath.

Looking at `LoginScreenViewModel` for example, it's using:

`@Injected(\.loginManager) var loginManager`

But it could just as well be using 

`var loginManager2 = DependencyInjection.assembly.loginManager`

It works exactly the same.

There doesn't seem to be any gain here over just keeping the old AppServices and making it a singleton... Or am I missing something?

**Comment by OskarGroth** [comment]
Also noted by a comment on the post by Ihor Vovk (that was quoted as inspiration for this change):

> Your implementation is intriguing in how you solved the mock/testing problem, but a bit lacking in that given the current implementation all you've done is create an indirect path to a set of singletons.
> 
> IOW, every single injection is going to be a reference to the same exact instance of an object. Without some sort of factory mechanism there's no way to build new, fresh objects when needed.

**Comment by davidgarywood** [comment]
Absolutely Oskar, it is essentially a fancy wrapper for a singleton. Individual items in the assembly can be overridden with mocks, as needed.

There are much more involved ways of configuring the property wrapper, and setting this up. It’s kinda beyond the scope of the post to get into the options. I may revisit this later on, but I’d be happy to see suggestions from others in forks of the repo!

**Comment by malhal** [comment]
You could have implemented a [custom environment value](https://developer.apple.com/documentation/swiftui/environmentkey) and made use of the built-in @Environment property wrapper. 

Apple implemented it this way for their loginManager named [authorizationController](https://developer.apple.com/documentation/swiftui/environmentvalues/authorizationcontroller?changes=latest_minor)
```
struct AuthorizationControllerExample: View {
    @Environment(\.authorizationController) private var authorizationController
```
